/*
    Generated by Atomist on 05 07 2016 
*/
package com.itb;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CompanyQuoteReceiverApplication {

    public static void main(String[] args) {
        SpringApplication.run(CompanyQuoteReceiverApplication.class, args);
    }
}
